// Song titles
const songsAlphabetical = [
	'100_porcento_voce',
	'acima_do_sol',
	'alo_paixao',
	'amor_de_chocolate',
	'amor_i_love_you',
	'amor_perfeito',
	'andanca',
	'assim_caminha_a_humanidade_malhacao',
	'baianidade_nago',
	'bailao',
	'baile_da_gaiola',
	'beleza_rara',
	'bola_de_sabao',
	'cilada',
	'de_ladinho',
	'depois_do_prazer',
	'deus_me_livre',
	'deusa_do_amor',
	'do_seu_lado',
	'dont_stop',
	'eva',
	'exagerado',
	'festa',
	'fico_assim_sem_voce',
	'final_feliz',
	'flor_do_reggae',
	'gatas_extraordinarias',
	'hey_jude',
	'i_love_you_baby',
	'i_miss_her',
	'ja_sei_namorar',
	'lua_de_cristal',
	'lucro',
	'mal_acostumado',
	'mania_de_voce',
	'maria_maria',
	'me_abraca_me_beija',
	'me_deixa',
	'meia_lua',
	'meu_sangue_ferve_por_voce',
	'milla',
	'nao_precisa_mudar',
	'nao_quero_dinheiro',
	'pintura_intima',
	'princesa',
	'sina',
	'sinais_de_fogo',
	'so_love',
	'sombra_da_maldade',
	'sorte_grande',
	'swing_da_cor',
	'tambem_quero_beijar_flor_do_maracuja',
	'temporal',
	'tempos_modernos',
	'tieta',
	'to_nem_ai',
	'toda_forma_de_amor',
	'tremendo_vacilao',
	'tu_ta_na_gaiola',
	'uma_noite_e_meia',
	'vai_novinha',
	'vai_sacudir_vai_abalar',
	'varias_queixas',
	'vem_meu_amor',
	'voce_me_vira_a_cabeca',
	'voce_nao_entende_nada'
];

const defaultPlaylistName = 'Ordem Alfabética';


const playlists = {
	'Ordem Alfabética': [...songsAlphabetical].sort(),
	'Novas 2026': [
		'sinais_de_fogo',
		'to_nem_ai',
		'amor_i_love_you',
		'vem_meu_amor',
		'i_miss_her'
	],
	'GIG': [
		'deusa_do_amor',
		'100_porcento_voce',
		'amor_perfeito',
		'depois_do_prazer',
		'meu_sangue_ferve_por_voce',
		'tempos_modernos',
		'nao_precisa_mudar',
		'varias_queixas',
		'bola_de_sabao',
		'temporal',
		'final_feliz',
		'ja_sei_namorar',
		'pintura_intima',
		'uma_noite_e_meia',
		'mania_de_voce',
		'tremendo_vacilao',
		'i_love_you_baby',
		'dont_stop',
		'baianidade_nago',
		'princesa',
		'amor_de_chocolate',
		'bailao',
		'baile_da_gaiola',
		'nao_quero_dinheiro',
		'assim_caminha_a_humanidade_malhacao',
		'toda_forma_de_amor'
	]
};

const caiu = [
	'coracao_radiante',
	'diga_que_valeu',
	'voa_voa',

]