// Song titles
const songsAlphabetical = [
  "100_porcento_voce",
  "acima_do_sol",
  "alo_paixao",
  "amor_de_chocolate",
  "amor_i_love_you",
  "amor_perfeito",
  "andanca",
  "assim_caminha_a_humanidade_malhacao",
  "baianidade_nago",
  "bailao",
  "baile_da_gaiola",
  "beleza_rara",
  "bola_de_sabao",
  "cilada",
  "de_ladinho",
  "depois_do_prazer",
  "deus_me_livre",
  "deusa_do_amor",
  "do_seu_lado",
  "dont_stop_michael_jackson",
  "eva",
  "exagerado",
  "festa",
  "fico_assim_sem_voce",
  "final_feliz",
  "flor_do_reggae",
  "gatas_extraordinarias",
  "hey_jude",
  "i_love_you_baby",
  "i_miss_her",
  "ja_sei_namorar",
  "lua_de_cristal",
  "lucro",
  "mal_acostumado",
  "mania_de_voce",
  "maria_maria",
  "me_abraca_me_beija",
  "me_deixa",
  "meia_lua",
  "meu_sangue_ferve_por_voce",
  "milla",
  "nao_precisa_mudar",
  "nao_quero_dinheiro",
  "pintura_intima",
  "princesa",
  "sina",
  "sinais_de_fogo",
  "so_love",
  "sombra_da_maldade",
  "sorte_grande",
  "swing_da_cor",
  "tambem_quero_beijar_flor_do_maracuja",
  "temporal",
  "tempos_modernos",
  "tieta",
  "to_nem_ai",
  "toda_forma_de_amor",
  "tremendo_vacilao",
  "tu_ta_na_gaiola",
  "uma_noite_e_meia",
  "vai_sacudir_vai_abalar",
  "varias_queixas",
  "vem_meu_amor",
  "voce_me_vira_a_cabeca",
  "voce_nao_entende_nada",
];

const defaultPlaylistName = "🔤 Ordem Alfabética";

const playlists = {
  "🔤 Ordem Alfabética": [...songsAlphabetical].sort(),
  "⭐ Assinatura": [
    "sombra_da_maldade",
    "tempos_modernos",
    "uma_noite_e_meia",
    "lua_de_cristal",
    "me_deixa",
    "exagerado",
    "dont_stop_michael_jackson",
    "i_love_you_baby",
  ],
  "✨ Novas 2026": [
    "sinais_de_fogo",
    "to_nem_ai",
    "amor_i_love_you",
    "vem_meu_amor",
    "i_miss_her",
    "coracao_partido",
  ],
  "🥂 GIG": [
    "deusa_do_amor",
    "100_porcento_voce",
    "amor_perfeito",
    "depois_do_prazer",
    "meu_sangue_ferve_por_voce",
    "tempos_modernos",
    "nao_precisa_mudar",
    "varias_queixas",
    "bola_de_sabao",
    "temporal",
    "final_feliz",
    "ja_sei_namorar",
    "pintura_intima",
    "uma_noite_e_meia",
    "mania_de_voce",
    "tremendo_vacilao",
    "i_love_you_baby",
    "dont_stop_michael_jackson",
    "baianidade_nago",
    "princesa",
    "amor_de_chocolate",
    "bailao",
    "baile_da_gaiola",
    "nao_quero_dinheiro",
    "assim_caminha_a_humanidade_malhacao",
    "toda_forma_de_amor",
  ],
  "🎭 Outras Carnaval": [
    "a_francesa",
    "alma_boemia",
    "amor_maior",
    "andei_so",
    "anunciacao",
    "ara_ketu_bom_demais",
    "arere",
    "asa_branca",
    "azul",
    "banho_de_folhas",
    "bate_lata",
    "bloco_na_rua",
    "boa_sorte",
    "canto_das_tres_racas",
    "canto_de_xango",
    "cheguei",
    "cobra",
    "danca_da_manivela",
    "eu_so_quero_um_xodo",
    "mama_africa",
    "medo_bobo",
    "o_canto_da_cidade",
    "ombrin",
    "palco",
    "palpite",
    "por_supuesto",
    "purpurina",
    "ta_escrito",
    "tristeza",
    "uma_brasileira",
    "vermelho",
  ],
};

const medleys = {
  "Medley Fritação": ["final_feliz", "ja_sei_namorar", "pintura_intima"],
  "Medley Ivete": ["eva", "alo_paixao", "beleza_rara"],
  "Medley Bahia/Deusa": ["deusa_do_amor", "100_porcento_voce", "amor_perfeito"],
  "Medley Divas": ["mania_de_voce", "tremendo_vacilao", "lua_de_cristal"],
  "Medley Lucro na Festa": ["lucro", "festa"],
  "Medley Botafogo": ["depois_do_prazer", "meu_sangue_ferve_por_voce"],
  "Medley Tim e Lulu (final)": [
    "nao_quero_dinheiro",
    "assim_caminha_a_humanidade_malhacao",
    "toda_forma_de_amor",
  ],
  "Medley Tropicaliente": [
    "tambem_quero_beijar_flor_do_maracuja",
    "tieta",
    "mal_acostumado",
  ],
  "Medley Banda Eva Classics": ["de_ladinho", "me_abraca_me_beija"],
  "Medley Funk": ["princesa", "amor_de_chocolate", "bailao", "baile_da_gaiola"],
  "Medley Claudinho & Buchecha": ["fico_assim_sem_voce", "so_love"],
  "Medley Caetano": ["meia_lua", "voce_nao_entende_nada"],
  "Medley Balanço Calmo": ["nao_precisa_mudar", "varias_queixas"],
  "Medley Beleza Pura": ["sina", "gatas_extraordinarias"],
};
